#pragma once

#include "./CC_PLATFORM_CPLUSPLUS.hpp"

#if CC_PLATFORM_CPLUSPLUS >= 202302L
    #define CC_CPP_STANDARD 23
#elif CC_PLATFORM_CPLUSPLUS >= 202002L
    #define CC_CPP_STANDARD 20
#elif CC_PLATFORM_CPLUSPLUS >= 201703L
    #define CC_CPP_STANDARD 17
#elif CC_PLATFORM_CPLUSPLUS >= 201402L
    #define CC_CPP_STANDARD 14
#elif CC_PLATFORM_CPLUSPLUS >= 201103L
    #define CC_CPP_STANDARD 11
#else
    #define CC_CPP_STANDARD 0
#endif